# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

copyToFinal <- function(curr_path) {
    invisible(.Call(`_ProjetAlgoTSP_copyToFinal`, curr_path))
}

secondMin <- function(adj, i) {
    .Call(`_ProjetAlgoTSP_secondMin`, adj, i)
}

TSPRec <- function(adj, curr_bound, curr_weight, level, curr_path, visited) {
    invisible(.Call(`_ProjetAlgoTSP_TSPRec`, adj, curr_bound, curr_weight, level, curr_path, visited))
}

TSP <- function(adj) {
    invisible(.Call(`_ProjetAlgoTSP_TSP`, adj))
}

rcpp_sum <- function(v) {
    .Call(`_ProjetAlgoTSP_rcpp_sum`, v)
}

